services:
  backend:
    image: ${IMAGE_FULL_URL}
    container_name: backend
    restart: always
    networks:
      - popi-net
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .env
  redis:
    image: "redis:alpine"
    container_name: redis
    networks:
      - popi-net
    environment:
      - TZ=Asia/Seoul
  nginx:
    image: "nginx:alpine"
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - popi-net
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

networks:
  popi-net:
    external: true
    name: popi-net