INSERT INTO notification (user_id, popup_id, item_id, item_name, popularity, min_stock, created_at, updated_at) VALUES
        (1, 1, 11, '[EUP23] BLACKPINK COLLECTIBLE FIGURE_JENNIE', 'HOT', 200, NOW(), NOW()),
        (1, 1, 5,  '[BLACKPINK THE GAME PHOTOCARD COLLECTION] BACK TO RETRO','HOT', 200, NOW(), NOW()),
        (1, 1, 6,  'BLACKPINK THE GAME PHOTOCARD COLLECTION LOVELY VALENTINES EDITION', 'NORMAL', 200, NOW(), NOW()),
        (1, 1, 7,  'BLACKPINK THE GAME PHOTOCARD COLLECTION CHRISTMAS EDITION','NORMAL', 200, NOW(), NOW()),
        (1, 1, 8,  'BLACKPINK THE GAME PHOTOCARD COLLECTION No.4~6 (SET)', 'NORMAL', 200, NOW(), NOW()),
        (1, 1, 15, '블랙핑크 (BLACKPINK) - 블랙핑크 더 게임 OST [THE GIRLS] Stella ver. (LIMITED EDITION)', 'NORMAL', 200, NOW(), NOW()),
        (1, 1, 17, '[INYOURAREA] KRUNK X BLACKPINK MINI CROSS BAG', 'NORMAL', 200, NOW(), NOW()),
        (1, 1, 22, '[INYOURAREA] KRUNK X BLACKPINK KEYRING', 'NORMAL', 200, NOW(), NOW());